force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>inov8__PMT_Project__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>inov8__PMT_Task__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Task_Account__c.field-meta.xml
<CustomField>
    <fullName>Task_Account__c</fullName>
    <formula>Task__r.PMT_Project__r.Invoice_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeEntrySetAccountBatch.cls
global class TimeEntrySetAccountBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Case__c, Case__r.AccountId, Task__c, Task__r.PMT_Project__c, Project__c, Project__r.Invoice_Account__c, Task_Account__c FROM Time_Entry__c WHERE Account__c = NULL';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<	Time_Entry__c > TimeEntries){
        for (Time_Entry__c TimeEntry : TimeEntries) {
            if (TimeEntry.Case__c != NULL && TimeEntry.Case__r.AccountId != NULL) {
                TimeEntry.Account__c = TimeEntry.Case__r.AccountId;
            } else if (TimeEntry.Project__c != NULL && TimeEntry.Project__r.Invoice_Account__c != NULL) {
                TimeEntry.Account__c = TimeEntry.Project__r.Invoice_Account__c;
            } else if (TimeEntry.Task__c != NULL) {
                if (TimeEntry.Project__c == NULL) {
                    TimeEntry.Project__c = TimeEntry.Task__r.PMT_Project__c;
                }
                TimeEntry.Account__c = TimeEntry.Task_Account__c;
            }
        }
        update TimeEntries;
    }

    global void finish(Database.BatchableContext bc){

    }

}